### ISSUE TITLE
[BUG] Issues with the new site

### ISSUE THREAD

**Issue by dontlaugh** [disease-sh/API#1006]
@maltejur Nice work on the new site!

Made an issue to shake out anything new in this transition. Looks good so far.

### Issues

* The docs link should go to https://disease.sh/docs/  (I believe)
* remove buy me a coffee link since it is being routed to someone who is unrelated to API dev for the last year

**Comment by puf17640** [comment]
thanks coleman! i wanted to do the same thing tomorrow morning! these things need to be adressed asap 👍
