### ISSUE TITLE
[BUG] Full vaccine data per country is showing 0

### ISSUE THREAD

**Issue by maltejur** [disease-sh/API#1008]
**Describe the bug**

The fields `daily`, `totalPerHundred` and `dailyPerMillion` all have a value of 0 on the `vaccine/coverage/countries?fullData=true` Endpoint.

**To Reproduce**
Visit https://disease.sh/v3/covid-19/vaccine/coverage/countries?lastdays=1&fullData=true

**Expected behavior**
I expect to see daily cases, cases per hundred and daily cases per million in the respective fields.

**Screenshots**
```json
{
    "country": "Afghanistan",
    "timeline": [
      {
        "total": 504502,
        "daily": 0,
        "totalPerHundred": 0,
        "dailyPerMillion": 0,
        "date": "5/18/21"
      }
    ]
  },
  {
    "country": "Albania",
    "timeline": [
      {
        "total": 680083,
        "daily": 0,
        "totalPerHundred": 0,
        "dailyPerMillion": 0,
        "date": "5/18/21"
      }
    ]
  },
```

**Additional context**
I need this because I would like to use relative numbers on the website.

**Comment by nibble0101** [comment]
@maltejur  and @ebwinters I don't think it is a bug. The only thing we try to calculate is the total from daily if there are missing values. The rest are left as reported by the source.  If  reported as `0` then the source is missing those values. You can check [here](https://github.com/disease-sh/API/blob/master/scrapers/covid-19/getVaccine.js#L164-L167).

**Comment by ebwinters** [comment]
@nibble0101 good catch. Closing the issue, thanks
