### ISSUE TITLE
just saw 19,481 "Critical" yet 35 deaths today USA. It's you doing it

### ISSUE THREAD

**Issue by balloonguy** [disease-sh/API#1021]
Maybe there's a reason worldometers, just your source that you know better than, lists it as "Serious OR Critical (that's a type of logic gate btw" and in the table as "Serious, Critical". You tech boys are having fun doing all this tech stuff, heart after heart, you are so passionate about things such as mere logic gates except the logic that is displayed directly to the public.

**Comment by ebwinters** [comment]
We are serving the exact data from the source:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/4297028/135780023-adb62e02-957c-4e23-a6d4-59f1c23c0a8b.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/4297028/135780031-2a0d9019-38ca-45fc-a618-49b2d9bbb7cc.png">

What is manipulated about what we are doing? There are no "logic gates" involved here.
