### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by anshbajpai** [disease-sh/API#1026]
Hi,
I am trying to access the following endpoint
(https://corona.lmao.ninja/v2/jhucsse)

but the API is responding with 502 bad gateway.

It's really important.
Thanks

**Comment by ustaslive** [comment]
@kajbo92 Thanks a lot! Worked for me

**Comment by PrincessRavy** [comment]
Do note that that domain has been deprecated for over a year, so uptime cannot be guaranteed. It currently runs on a personal server with no active monitoring.
