### ISSUE TITLE
Ship an additional, lexically-sortable docker tag

### ISSUE THREAD

**Issue by dontlaugh** [disease-sh/API#1034]
We are upgrading the version of flux we use to deploy our APIs. Moving from flux1 to flux2.

Flux2 changes it's automatic image detection. It now requires either semver, lexical sorting, or numeric sorting.

* semver (get the latest within a range)
* alphabetical (asc/desc)
* numerical (asc/desc)

Here is the main docker repo https://hub.docker.com/r/novelcovid/novelcovid-api/tags

Note that tags are of the form `sha-{short hash}`. During this transition period, I propose the following:

* Continue pushing the same tags `sha-{short hash}`, so existing production isn't affected
* In CI, create an additional tag, using some sortable format.

Given the nature of this project, CalVer might be a good choice.

https://calver.org/

----

We'll open more issues as we need to. Right now it looks like most things can be handled transparently by ops in the background. Ping us in chat if you have any questions. cc @bcmendoza @alecholmez @tilleryd

**Comment by ebwinters** [comment]
Right now we are using the [build push publish action](https://github.com/docker/build-push-action). It looks like it supports semver out of the box. Would {Major}.{Minor} work?


<img width="568" alt="image" src="https://user-images.githubusercontent.com/4297028/152374659-7cbdc661-33f4-4cfb-82aa-210f88e2a8e6.png">

**Comment by bcmendoza** [comment]
@ebwinters Yes, that would work. But it seems like the deployment strategy is using the SHA tags -- likely to track with the latest changes vs just version releases. If you want the latest images auto-deployed, we'll need to move to CalVer.

**Comment by bcmendoza** [comment]
This seems to be the tagging strategy we want to go with: https://github.com/docker/metadata-action#typeschedule

**Comment by ebwinters** [comment]
so we want the tags to look like `2021-02-04-23-53` instead of `sha-49a86a6`

**Comment by ebwinters** [comment]
@PrincessRavy will this change affect your webhook for pulling latest image?

**Comment by ebwinters** [comment]
@bcmendoza linked PR check it out, seems that format is supported out of the box with the action we are using

**Comment by PrincessRavy** [comment]
don't think so, webhook builds from source

**Comment by bcmendoza** [comment]
@ebwinters Thanks for the PR! I left a comment there. We'll need to support both tag formats for the meantime until we can fully migrate over to Flux 2.
