### ISSUE TITLE
[Feature Req] Monkeypox Api please? 

### ISSUE THREAD

**Issue by Dooks123** [disease-sh/API#1053]
**Is your feature request related to a problem? Please describe.**
Nope, no problem.

**Describe the solution you'd like**
An endpoint for Monkeypox cases please

**Additional context**
Same output as Covid apis, All, Countries yesterday and today

**Comment by ebwinters** [comment]
Great idea. Let's see if I can get some traction on this from community. Give me a bit

**Comment by pujux** [comment]
Doesn't seem like any traction built up 😆 I'll close this for now as it's not relevant anymore, is it?
