### ISSUE TITLE
[BUG] the link for one of badges broken in readme.md

### ISSUE THREAD

**Issue by samtaitai** [disease-sh/API#1056]
**Describe the bug**
Hi, first I'd like to say that this is a really cool project!
I happened to find that the badge called 'Visits' has a broken link in README.md

**To Reproduce**
the broken link is this: https://badges.pufler.dev/visits/disease-sh/api?style=for-the-badge
it said that web server is down (error code 521). 

**Expected behavior**
Recovering the link would be nice. 

**Screenshots**
please find additional context for it.

**Additional context*
![brokenlink](https://user-images.githubusercontent.com/15338728/197851215-9358fc58-baad-4db3-83ab-21d9671a3ff4.PNG)
*
![errorcode521](https://user-images.githubusercontent.com/15338728/197851263-ba7a3b96-bf1a-4167-903d-3884d511e797.PNG)

**Comment by puf17640** [comment]
thanks for noticing, this is my server. but I currently just don't have the time to keep it up and maintain it. it will be back up again some time

**Comment by TriptiAroraa** [comment]
Hey! i want to work on this issue .May i?

**Comment by pujux** [comment]
this has already been fixed
