### ISSUE TITLE
[BUG] JHUCSSE Recovered data are not trustworthy

### ISSUE THREAD

**Issue by Ahmed-UPEC** [disease-sh/API#1057]
I am currently building a PyQT App for my Master and I have to create a Covid traker APP. After fetching data from https://disease.sh/v3/covid-19/historical/ end-point. I can see in my plots that the recovered data are not trustworthy. 
Is it me or the recovered data should be neglected.

![image](https://user-images.githubusercontent.com/56971722/199298030-f02afa66-95f8-459b-af91-7d1d7a7f1994.png)

**Comment by ebwinters** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/4465

JHU stopped maintaining recovered data on Aug 4 2021 , as seen above
