### ISSUE TITLE
[BUG] Cloudflare is reporting site is down

### ISSUE THREAD

**Issue by eightseventhreethree** [disease-sh/API#1073]
**Describe the bug**
Cloudflare is reporting the site is down.

**To Reproduce**
Where the bug occurring? Examples:
- Go to: https://disease.sh/
- Cloudflare error page 502 Bad Gateway appears.

**Expected behavior**
Cloudflare does not display 502 Bad Gateway

**Screenshots**
<img width="1042" alt="Screenshot 2023-06-15 at 6 25 36 AM" src="https://github.com/disease-sh/API/assets/12215946/b6e435fd-e325-415e-a237-cb3d393bac87">

**Additional context**

**Comment by ebwinters** [comment]
Looks like it's back
