### ISSUE TITLE
[BUG] REST API call fails with 502 bad gateway. How is to overcome this?

### ISSUE THREAD

**Issue by PurnaChandraPanda** [disease-sh/API#1078]
**Describe the bug**
URI access fails with 502 for queries like - https://disease.sh/v3/covid-19/countries/Argentina,USA.

**To Reproduce**
Where the bug occurring? Examples:
- Live URL for endpoint? Access URI https://disease.sh/v3/covid-19/countries/Argentina,USA in browser or postman or curl get, it will fail with 502 bad gateway.
- Server side? 502 gateway
- Development environment?

**Expected behavior**
Expecting 200 for rest api calls.

**Screenshots**
<img width="706" alt="image" src="https://github.com/disease-sh/API/assets/18218128/c07c7fde-a9d5-434f-861c-b417f1672d99">

**Comment by pujux** [comment]
it's best to ask in the discord if something with the public instance is not working correctly
