### ISSUE TITLE
[Feature Req] Add possibleNames field to a country's countryInfo object

### ISSUE THREAD

**Issue by MarvelDC** [disease-sh/API#728]
**Is your feature request related to a problem? Please describe.**
To reduce myself having to query `/countries/:query` each time I want to find a country, that can have aliases, having a way to view the possible names of a country will allow me to simply query the `/countries` endpoint once (when cached), and find the country in the array of countries.

**Describe the solution you'd like**
Using `possibleNames` array from [`utils/countries.js`](https://github.com/NovelCOVID/API/blob/master/utils/countries.js).
`/countries/:query` and `/countries` endpoint:
No data:
```json
"countryInfo": {
    "_id": null,
    "iso2": null,
    "iso3": null,
    "lat": 0,
    "long": 0,
    "flag": "https://disease.sh/assets/img/flags/unknown.png",
    "possibleNames": []
  },
```
With data (UK for example):
```json
"countryInfo": {
    "_id": 826,
    "iso2": "GB",
    "iso3": "GBR",
    "lat": 54,
    "long": -2,
    "flag": "https://disease.sh/assets/img/flags/gb.png",
    "possibleNames": ["England", "United Kingdom"]
  },
```
Please don't standardize the possible names.
**Additional context**
Before, I'd have to fetch `/countries/england` each time, but now with my already cached `/countries/` data, I can just search the array of countries that meet the possible names.

Probably something like this in [`utils/countryUtils.js`](https://github.com/NovelCOVID/API/blob/master/utils/countryUtils.js).
```javascript
return countryFound ? {
		_id: countryFound.id,
		country: countryFound.country,
		iso2: countryFound.iso2,
		iso3: countryFound.iso3,
		lat: countryFound.lat,
		long: countryFound.long,
		flag: `https://disease.sh/assets/img/flags/${countryFound.iso2.toLowerCase()}.png`,
                possibleNames: countryFound.possibleNames || []
	} : nullReturn;
```
Having the no possible names as an empty array is just making it easier when searching client-side, but I'm OK with it being `null`.

**Comment by ebwinters** [comment]
This is a good request, but first and foremost we cannot discontinue the standardization of possible names. This is what allows people to make queries without having the entire countries JSON file, which when returned, is large. 

I will look into the possibility of adding `possibleNames` as a feature

**Comment by puf17640** [comment]
Very cool idea! Let's add this to the topics of the discussion today @ebwinters

**Comment by puf17640** [comment]
So me and @ebwinters just discussed this and we think that the possiblenNames would not be needed to have sent with the response but after that we discussed adding more possibleNames to the countries and making it possible to leave out whitespaces in names (like "United States Of America" -> "UnitedStatesOfAmerica")

**Comment by ebwinters** [comment]
@MarvelDC if you have any ideas of countries that are currently missing a possible name in [this file](https://github.com/NovelCOVID/API/blob/master/utils/countries.js) that would be helpful!

**Comment by MarvelDC** [comment]
> @MarvelDC if you have any ideas of countries that are currently missing a possible name in [this file](https://github.com/NovelCOVID/API/blob/master/utils/countries.js) that would be helpful!

I wouldn't know any as of now, but [this Wikipedia page](https://en.m.wikipedia.org/wiki/List_of_alternative_country_names) does seem to sum up the possible names of many countries.

**Comment by ebwinters** [comment]
Any chance you want to add them into the file mentioned above, and submit PR? @MarvelDC
