### ISSUE TITLE
Use Webp or SVG types for images instead of png and jpg.

### ISSUE THREAD

**Issue by MenaiAla** [disease-sh/API#768]
**Description :**

After checking the `public/assets/img` folder I've noticed that it contains `png` and `jpg` images instead of `webp` or `svg`

*Expected issues:**

 * Lose quality in small screens.
 * Large size and low performance.
 * Impossible to redesign the same file ( Image

**Comment by puf17640** [comment]
Feel free to convert them and file a PR! 👍

**Comment by ebwinters** [comment]
any update on this @MenaiAla

**Comment by MenaiAla** [comment]
@ebwinters trying to test the performance between the two different extensions ( png vs webp ).

**Comment by meirroth** [comment]
Can we have a few file type options or does it have to be one of them?
Currently, I'm using svg flags from this repo: [ behdad / region-flags ](https://github.com/behdad/region-flags)

**Comment by ebwinters** [comment]
@meirroth we can have a few options, with the default being PNG (so as not to mess with peoples' current use of flags). But we can add a query parameter for `fileType`, which would allow for a link to an SVG to be returned. Personally, I am not going to implement this, but if someone else wants to, PRs are welcome.

**Comment by apex2504** [comment]
this is a few days old now but compatibility could be an issue as some apple devices (specifically iOS/iPadOS - i believe macOS 11 is introducing support) don't support webp images and they simply won't be shown. to ensure the best compatibility, it would make sense to still use jpg/png, or at least include them as an option alongside webp/svg in some way.

**Comment by puf17640** [comment]
we could just convert it, it will get cached anyway?

**Comment by ebwinters** [comment]
Unless I see a benchmark that shows it would be worth storing multiple file types, this will be closed.

**Comment by puf17640** [comment]
> we could just convert it, it will get cached anyway?

**Comment by buster95** [comment]
this is a bot for image reduction, maybe could be integrated here
https://github.com/marketplace/imgbot/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNzQ5#pricing-and-setup

**Comment by ebwinters** [comment]
Does it provide an real speed benefits to convert every PNG to SVG or another format? Once we have that answered then we can decide on moving forward or not with this

**Comment by puf17640** [comment]
@Nekiono surely already has done a benchmark at some time in her life i suppose

**Comment by ebwinters** [comment]
closing for now

**Comment by MenaiAla** [comment]
@puf17640 , what do you think about [gulp](https://gulpjs.com/), it optimizes images.
