### ISSUE TITLE
[Feature Req] Israel data

### ISSUE THREAD

**Issue by ebwinters** [disease-sh/API#769]
**Is your feature request related to a problem? Please describe.**
Israel gov scraper, with links sent on discord: 
[Dashboard](https://datadashboard.health.gov.il/COVID-19/)
[Translation](https://media.discordapp.net/attachments/727682901881389137/727930855451918496/Hebrew_translation.png)

**Describe the solution you'd like**
I’m going to write the scraper, this is so I don’t forget.

**Comment by puf17640** [comment]
nice!
