### ISSUE TITLE
Why there's double country.country[BUG] ?

### ISSUE THREAD

**Issue by MenaiAla** [disease-sh/API#771]
**Javascript Syntax**

In the line of 14 of [apiWorldometers.js](https://github.com/disease-sh/API/blob/master/routes/v3/covid-19/apiWorldometers.js) we have double access to the country.

`const worldData = countries.find(country => country.country.toLowerCase() === 'world');`

I know the first one is a country `parameter` but I don't know what's the second one.

**Comment by ebwinters** [comment]
Believe it is the name of the country itself. Maybe change name of parameter to make it more clear, or change the property to `countryName`

**Comment by puf17640** [comment]
> Believe it is the name of the country itself. Maybe change name of parameter to make it more clear, or change the property to `countryName`

we cannot rename properties, we could only call the first one 'countryData' instead of 'country' to make it more distinguishable.

**Comment by shashwat1998** [comment]
Assign it to me please
