### ISSUE TITLE
How transformNull transform a continent/country object into null ?

### ISSUE THREAD

**Issue by MenaiAla** [disease-sh/API#775]
I'm trying to understand how  `transformNull` function in `utils/countryUtils` transform a continent/country `object` into `null`.

Please, provide me an example with `input` and `output`.

**Comment by ebwinters** [comment]
I guess the function is kind of confusing and can be refactored. All this does is transform a value from 0 to null. If we are missing data for say deaths of a country, we fill it with 0. This just allows for null instead

**Comment by puf17640** [comment]
definitely not a bug. feel free to refactor the method if you think it needs a cleanup.

JSDOC explains it though.
```
/**
 * Transform null values to 0 (DEEPLY TRANSFORM)
 * @param {Object} object country/continent object
 * @returns  {Object} 		transformed object
 */
```

**Comment by MenaiAla** [comment]
Indeed, it's a **fatal bug** because even `null` value is an `object`.

**Reproduce by example**
`
console.log(typeof null)`

**Output**
`object`

**Description** 
If the object passed is a `null` value the condition will pass. Also, if the `value` passed has `length` equals `0` the condition will pass.

**Comment by puf17640** [comment]
`null` is only 'an object' because of bad design decisions when JS first started and is definitely not handled like an object in practice. 

If you pass in `null`, the function throws an error (check below) because **null is not an object**, so you can't convert it to one (`Object.entries(object)`). The function works as it should for all inputs that are possible in our code.

![image](https://user-images.githubusercontent.com/17516174/86611275-c182a200-bfae-11ea-8566-cb87b0b23e48.png)

**Comment by MenaiAla** [comment]
But this is **Unhandled** exception and `null` value pass the check because you wrote `typeof o==="object"` and in case of `o===null` the check will be : `typeof null==="object"` and that's correct. But, in real-world with `null` values we should handle `exceptions`.

This is a quick-refactoring for `transformNull` function with well-debugging status but without unit-testing : 
```

const convertNullToZero = (continentOrCountry = null) => {

    const COUNTRY_INFO = 'countryInfo';

    if (typeof continentOrCountry !== "object" || !continentOrCountry) {

        throw new TypeError(`${continentOrCountry}` + "should be a an object with non null value")

    }
    if (Object.keys(continentOrCountry).length === 0) {
        throw new Error(`${continentOrCountry}` + "should not be an empty object")
    }

    Object.entries(coc).forEach((entry) => entry[0] !== COUNTRY_INFO && (coc[entry[0]] = entry[1] === null ? 0 : convertNullToZero(entry[1])));

    return object;
};
```

**Comment by puf17640** [comment]
You'll probably find a hell lot of unhandled exceptions because me and @ebwinters didn't bother to do exception handling apparently, if you want you can go over the code and PR your changes, would help a lot

**Comment by MenaiAla** [comment]
Sur, just trying to be familiar with each script and understand the whole project.
