### ISSUE TITLE
[BUG] Why wordsStandardize returns 'null' but not null ?

### ISSUE THREAD

**Issue by MenaiAla** [disease-sh/API#777]
**Description**

In [stringUtils](https://github.com/disease-sh/API/blob/master/utils/stringUtils.js) script line `6` :
`const wordsStandardize = (word) => word ? word.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '') : 'null';`

**Expected**
`null`

**Found**
`'null'`

**Comment by puf17640** [comment]
I am [blaming](https://github.com/disease-sh/API/commit/c65bfae1601879f457ab5092a803889f21670e01#diff-20510c60361f45829ec242bf65259fd0R6) @buster95 🤣 

Will be fixed in a minute! Thanks for letting us know!

**Comment by puf17640** [comment]
![image](https://user-images.githubusercontent.com/17516174/86595414-fab01780-bf98-11ea-9b51-e9e6a334d3d4.png)
now I remember why 🤣 🤣 will be fixed soon

**Comment by buster95** [comment]
> I am [blaming](https://github.com/disease-sh/API/commit/c65bfae1601879f457ab5092a803889f21670e01#diff-20510c60361f45829ec242bf65259fd0R6) @buster95 🤣 
> 
> Will be fixed in a minute! Thanks for letting us know!

Hahahahaha oi, that was when you were doing code refactoring hahah

**Comment by puf17640** [comment]
this is already fixed in #779
