### ISSUE TITLE
[BUG] How splitQuery handle null queries and queries without | or , ?

### ISSUE THREAD

**Issue by MenaiAla** [disease-sh/API#781]
**Description**
`splitQuery `function is kind of uncomplete and does not treat all cases. It supposes that the parameter `query`  contains `|` or `,` as a splitter. But what if the query does not have both of the splitters.

**Reproduction**
`const splitQuery = (query) => query.indexOf('|') === -1 ? query.split(',') : query.split('|');`
`const query=null`;
`console.log(splitQuery(query))`

**Expected behavior**
An array of characters or strings.

**Real-world behavior**
`Uncaught TypeError: Cannot read property 'indexOf' of null`

**Additional context**
`const splitQuery = (query) => query.indexOf('|') === -1 ? query.split(',') : query.split('|');`
`const query="usa"`;
`console.log(splitQuery(query))`

**Comment by ebwinters** [comment]
Would `null` ever even be passed to this function?
https://disease.sh/v2/countries/null|null
https://disease.sh/v2/countries/null
https://disease.sh/v2/countries/usa,null

All of these results are as expected...
