### ISSUE TITLE
[BUG] Israel Gov data returns 0 for updated timestamp

### ISSUE THREAD

**Issue by meirroth** [disease-sh/API#783]
**Describe the bug**
Israel gov data endpoint (https://disease.sh/v3/covid-19/gov/Israel) returns 0 for updated time. 
`{
  "updated": 0,
  "data": {
... 
  }
}
`

**To Reproduce**
Where the bug occurring? Examples:
- https://disease.sh/v3/covid-19/gov/Israel

**Expected behavior**
Expected to get updated time.
`{
  "updated": 1594569303303,
  "data": {
... 
  }
}
`

**Additional context**
I checked if the government API has changed the query or something but it looks the same.

Then I checked the [scraper](https://github.com/disease-sh/API/blob/master/scrapers/covid-19/govScrapers/getIsrael.js) and I saw that in [this commit](https://github.com/disease-sh/API/commit/c969a8f8b628241bf905d2a6b3d256938f84ff64#diff-3990eaa03a337e3af1a6a50dd859c910L6) the line that is responsible for getting the updated timestamp was edited,
I tested it on my local machine with this commit reverted and there was no issue.
Hey @puf17640, What was the reason for the query parameters to be stripped off? It seems to be causing the issue.
 
Thanks.

**Comment by ebwinters** [comment]
The `single` parameter for the POST request was removed, which would tell the API a single value is returned instead of an object or array. PR fixes this.

**Comment by meirroth** [comment]
Thank you Ethan!

**Comment by puf17640** [comment]
Oh! I actually remember it working when I tested it in Postman, thats why I took out the stuff that I thought wasn't needed back then. My bad!! 😳
