### ISSUE TITLE
[Feature Req] ESlint : Replace --ignore-pattern by .eslintignore file

### ISSUE THREAD

**Issue by MenaiAla** [disease-sh/API#787]
### Source
Package.json

### Found
`eslint ./**/*.js --fix --ignore-pattern node_modules/"`

### Suggested
- [x] Create `.eslintignore.js` file. 
- [x] Add folders and files that will be ignored.

**Comment by puf17640** [comment]
Should I assign you?

**Comment by MenaiAla** [comment]
Opened a PR #789 .
