### ISSUE TITLE
[Feature Req] Why  countryExceptions is file-scoped variable.

### ISSUE THREAD

**Issue by MenaiAla** [disease-sh/API#788]
### Source
countryUtils

### Line
87

### Found
```
const countryExceptions = ['UK', 'UAE', 'DR'];
/**
 * Check for country exception when searching countries
 * @param 	{string} 	countryname 	name of the country to be searched
 * @returns {boolean}
 */
const isCountryException = (countryname) => !!countryExceptions.find(exception => stringUtils.wordsStandardize(countryname) === stringUtils.wordsStandardize(exception));
```
### What-If
`
const isCountryException = (countryname, countryExceptions = ['UK', 'UAE', 'DR'])`

**Comment by puf17640** [comment]
we can just completely remove countryExceptions variable and hardcode the array, i see no reason to add a parameter to the function that wont be used for anything other than assign a variable that is only used once
