### ISSUE TITLE
JHU Spain subdivisions | deaths+recovered > confirmed [BUG]

### ISSUE THREAD

**Issue by karimhb** [disease-sh/API#792]
**Describe the bug**
JHU Spain subdivisions return incorrect data. For some subdivisions `deaths+recovered > confirmed` which can't possibly be correct. Even if the subdivision has 0 active cases, the total of deaths + recovered would become = confirmed, but never higher!

**To Reproduce**
Where the bug occurring? Examples:
https://corona.lmao.ninja/v3/covid-19/jhucsse
**As of the time of reporting the bug:**
  - Cantabria => "confirmed":2380,"deaths":216,"recovered":2287
  - Galicia => "confirmed":9479,"deaths":619,"recovered":9204
  **Number of recovered patients is higher than the total number of patients ever infected!**
  - Murcia => "confirmed":1771,"deaths":148,"recovered":2180 
  - Pais Vasco => "confirmed":14099,"deaths":1563,"recovered":16160
  - Ceuta => "confirmed":164,"deaths":4,"recovered":163

**Expected behavior**
`deaths+recovered =< confirmed`

**Comment by ebwinters** [comment]
This is an anomaly in the data being reported by JHU. That said, we are just reporting a cleaned up version of their exact data. 
[Here](https://github.com/RamiKrispin/coronavirus/issues/55) is a link to an issue in their repo with good descriptions as to why it is happening, which should answer your question.
