### ISSUE TITLE
How can I get history of cases by specific datetime range?

### ISSUE THREAD

**Issue by jdahan91** [disease-sh/API#793]
Hi, I am using the following url to get statistics for the country I live at, but I would also like to get history of cases by specific datetime, is it possible? 

`https://disease.sh/v3/covid-19/countries/israel`

I've seen this model

country | string
-- | --
province | string

But I'm not sure how to construct it with the current url i'm using, thanks. (POST maybe?)

**Comment by jdahan91** [comment]
Nevermind, I saw that there's an api for histogram cases.

**Comment by ebwinters** [comment]
Yep. Also check out https://disease.sh/v3/covid-19/gov/Israel

**Comment by jdahan91** [comment]
> Yep. Also check out https://disease.sh/v3/covid-19/gov/Israel

Wow... this api is exactly what I was looking for, which contains data about quarantine. Thank you so much.

**Comment by puf17640** [comment]
If you need anything else, don't hesitate to ask or join our support discord (can be found in the README)
