### ISSUE TITLE
[BUG] /v3/covid-19/gov/{country} for Israel not working

### ISSUE THREAD

**Issue by jdahan91** [disease-sh/API#794]
I'm getting 404 for Israel when using the following api, yesterday it worked but today it's not.

raw response:

```
{
  "message": "Country 'Israel' not found or no data found for country"
}
```

**Comment by ebwinters** [comment]
When I test locally and re-scrape, everything works as it should. However, I do see in the live API that the specific endpoint is returning the message you posted above. The data must have been misformatted when scraping the last time, so we can try and reach out to the company who runs our infrastructure and restart the micro-service.

**Comment by jdahan91** [comment]
I'm migrating my mobile app to depend on these apis instead, so i need them working ;]

**Comment by ebwinters** [comment]
Yeah they will work; https://disease.sh/v3/covid-19/gov/Israel is running again.

**Comment by jdahan91** [comment]
Ethan tell me something, is it possible to request a custom made api with a specific data structure of data i'm interested in? even if it's to share this api with my privately i would still thank you for it.

**Comment by ebwinters** [comment]
Well, you can either process the data on your end, or self host the API and edit the structure. We will not change it

**Comment by jdahan91** [comment]
I understand, ok. Thank you anyways for restarting the micro-service, case can be closed.

**Comment by jdahan91** [comment]
This api is down again =/, any idea what causes it to go down? i need it up 100% because i rely on this api.

if this continue happening i'd might have to migrate to a different api.

**Comment by ebwinters** [comment]
I'm gona make a bug fix right now so the data is always hosted even if the Israel government source is faulty.

**Comment by jdahan91** [comment]
> I'm gona make a bug fix right now so the data is always hosted even if the Israel government source is faulty.

Thank you.

**Comment by ebwinters** [comment]
#796

**Comment by ebwinters** [comment]
What do you rely on this API for, just curious @jdahan91

**Comment by jdahan91** [comment]
> What do you rely on this API for, just curious @jdahan91
> 
> Give the API time to re scrape, and once it does it will never serve an error again

https://github.com/jdahan91/Covid19Tracker-for-Israel-Preview

This app uses this endpoint to show the events in the selected date from the list. i'm actually using three endpoints from disease.sh and another one from feel.co.il.

The listview is populated using feel.co.il and the rest of the app relies on disease.sh.

I know it is not a good practice to show details from two different endpoints but each one delivers a different use case for my Models.

**Comment by ebwinters** [comment]
It's working @jdahan91
