### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vlasischar** [disease-sh/API#795]
At Australia historical endpoint, at the deaths section, in "6/1/20", the number of the deaths goes from 103 to 102

**Endpoint**
https://corona.lmao.ninja/v2/historical/Australia?lastdays=350

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/28724624/88274803-f5670280-cce4-11ea-8653-c7798f171a08.png)

**Comment by puf17640** [comment]
We only scrape and reserve data, this particular dataset is from JHU CSSE (https://github.com/CSSEGISandData/COVID-19) so please open an issue on their repository
