### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by MorkWood2** [disease-sh/API#798]
The API's are no longer working, the server seems down.
![disease](https://user-images.githubusercontent.com/28037374/88493148-75e76680-cf64-11ea-9db9-28d1f02476c8.png)
Also getting plenty of CORS Policy errors. 
![errors](https://user-images.githubusercontent.com/28037374/88493188-a6c79b80-cf64-11ea-8089-225ad0cf770c.png)
Anyone else getting these errors? 

Thanks.

**Comment by ebwinters** [comment]
yep, looking into it. Should be fixed within 15 min

**Comment by MorkWood2** [comment]
Awweesome, Thank you!

**Comment by ebwinters** [comment]
back up!
