### ISSUE TITLE
Add New API Endpoint for specific set of Continents from Worldometers 

### ISSUE THREAD

**Issue by zekinah** [disease-sh/API#801]
**Is your feature request related to a problem? Please describe.**
Currently, we have an API endpoint that is from Worldometers that gets Covid-19 totals for a specific set of countries in which you can load specific countries in just adding query parameters such as multiple country names, iso2, iso3, or country IDs separated by commas which is like this `https://disease.sh/v3/covid-19/countries/PH%2C%20USA`.
We also have that loads all of the data of all continents which is this `https://disease.sh/v3/covid-19/continents` and that loads a specific for a continent which is this `https://disease.sh/v3/covid-19/continents/North%20America`.

**Describe the solution you'd like**
Now we can have an endpoint putting query parameters for continents separated by a comma and that should look like this. `https://disease.sh/v3/covid-19/continents/Asia%2CNorth%20America`,  and that should only load the data of a specific set of continents.

**Comment by puf17640** [comment]
I actually thought I added that in but I guess I did not. Working on it.

**Comment by zekinah** [comment]
Nice one, a very nice quick touch.  Thanks, @puf17640
