### ISSUE TITLE
[BUG] Israel Gov endpoint returning 404 Not Found (disease.sh)

### ISSUE THREAD

**Issue by meirroth** [disease-sh/API#803]
**Describe the bug**
https://disease.sh/v3/covid-19/gov/israel
Returning 404 not fount with the message "Country 'Israel' not found or no data found for country"

**To Reproduce**
Where the bug occurring? Examples:
- https://disease.sh/v3/covid-19/gov/israel

**Expected behavior**
This endpoint seems to be working fine:
https://corona.lmao.ninja/v3/covid-19/gov/israel

**Comment by ebwinters** [comment]
The scrape must have failed on that server. I'm not sure why the scraping fails for that server all the time, but it's the Israeli government source that is returning bad response. I tried to fix this but the fix ended up not working so reversed.

**Comment by meirroth** [comment]
How come it still works on https://corona.lmao.ninja/v3/covid-19/gov/israel?

**Comment by ebwinters** [comment]
We need a way to make sure that if the data returns 404 the previous data is served.

**Comment by puf17640** [comment]
@ebwinters can we talk about this tomorrow in a hangout call?

**Comment by ebwinters** [comment]
@puf17640 Yes
@meirroth its on a different server.

**Comment by meirroth** [comment]
Yea but isn't it running the same code?

Anyhow, I have switched my dashboard to use corona.lmao.ninja as the endpoint for now. Hope it lasts
Thank you both so much for maintaining this API, you guys are awesome!

**Comment by ebwinters** [comment]
It's the same code ye, but each server makes a request o Israel's source. The source returns a 404 sometimes in that request.

**Comment by meirroth** [comment]
https://disease.sh/v3/covid-19/gov/israel Is working now.
