### ISSUE TITLE
[Feature Req] Mexico gov endpoint

### ISSUE THREAD

**Issue by Collin-St** [disease-sh/API#810]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A /gov endpoint for Mexico data

**Additional context**
Source: https://coronavirus.gob.mx/datos/
- Gathering the cases/deaths for national and state totals requires making ~4 requests to their server with specific form-data. I can share a postman collection with the requests laid out.

Terms of Service: https://www.gob.mx/salud/documentos/datos-abiertos-152127
- this page states that this data source is open for free use, reuse, and redistribution.

**Comment by ebwinters** [comment]
The terms of service look good, I would just make sure to site it as the source in the endpoint's return value somewhere. @Collin-St You can work on it and make a PR 👍

**Comment by Collin-St** [comment]
#811
