### ISSUE TITLE
UK Data no longer being collected

### ISSUE THREAD

**Issue by 1CM69** [disease-sh/API#812]
In their infinite wisdom the UK government has decided to change the API endpoints as of today & this has now broken the URLs in disease.sh.

[https://disease.sh/v3/covid-19/countries/uk](https://disease.sh/v3/covid-19/countries/uk)

returns 0 deaths for today & the cumulative deaths figure is from yesterday.

[https://disease.sh/v3/covid-19/gov/uk](https://disease.sh/v3/covid-19/gov/uk)

only returns data from 1st August as the latest result.

**Comment by 1CM69** [comment]
I have been through the new API docs on the UK governments website: [https://coronavirus.data.gov.uk/developers-guide](https://coronavirus.data.gov.uk/developers-guide)

and figured the basic URL for up to date data is: [https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=overview&structure={"date":"date","deaths":{"daily":"newDeathsByPublishDate","cumulative":"cumDeathsByPublishDate"}}](https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=overview&structure={"date":"date","deaths":{"daily":"newDeathsByPublishDate","cumulative":"cumDeathsByPublishDate"}})

hope this helps

**Comment by ebwinters** [comment]
Thanks for the write up, I won't have time to work on this but I'll make it known to the community!
