### ISSUE TITLE
api returns old data sometimes

### ISSUE THREAD

**Issue by nooblyf** [disease-sh/API#815]
On page refresh sometimes it returns old data, like on my website it would say 18,722,090 cases then it would jump back to 18,721,965 cases. I'm using the `/v3/covid-19/all` endpoint.

**To Reproduce**
- go to https://disease.sh/v3/covid-19/all?yesterday=false
- hit refresh couple of times

**Expected behavior**
Once new data is available it should not jump back to old one.

**Screenshots**
As seen here:

![se39841207b0](https://user-images.githubusercontent.com/54323745/89394193-679a0700-d729-11ea-84e5-d0cd25cd8561.gif)

**Comment by ebwinters** [comment]
This has to do with caching, which is necessary for any large scale API. If you want to bust the cache, and get the most up to date data, just add a cache buster (`?t=1`)

**Comment by nooblyf** [comment]
@ebwinters i understand that but using &t=1 does not work, any other solution?
btw thanks for keeping this awesome api free 🎉

**Comment by ebwinters** [comment]
Is it still happening?

**Comment by nooblyf** [comment]
@ebwinters yes it's still happening, i tried this `https://disease.sh/v3/covid-19/all?yesterday=false&t=1` but no luck.

**Comment by ebwinters** [comment]
@nooblyf how about not having a yesterday param at all? If it's false, just don't include it
