### ISSUE TITLE
[Feature Req] Google mobility report

### ISSUE THREAD

**Issue by CovidMexico** [disease-sh/API#822]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add data from the Google mobility reports (COVID-19). 

**Additional context**
The API has the mobility information from Apple, this feature is for the Google reports.
The official Google reports are here: https://www.google.com/covid19/mobility/
Also this CSV could be useful: https://github.com/owid/covid-19-data/tree/master/public/data/gmobility

**Comment by Collin-St** [comment]
The only way I can see this getting into the API is by biting the bullet and fetching/parsing this massive 123 MB csv directly from Google. Unfortunately I can't find the data available anywhere else, and the PDFs for individual regions are useless for this purpose. Also not sure about fetching the CSV from that repo you linked.

I defer to @ebwinters and others

**Comment by ebwinters** [comment]
I remember we talked about this at one point and decided against it. Not sure if I remember why though @puf17640 was the one who looked into it

**Comment by puf17640** [comment]
the data provided is not consistant as to that they publish each days data on the day after, the currently most up to date report is from 3 days ago
