### ISSUE TITLE
Re-direct v2 routes to v3 using Express

### ISSUE THREAD

**Issue by ebwinters** [disease-sh/API#831]
We have many high profile users who are unreachable, and are still using v2. Because of this, we will redirect v2 endpoints to their corresponding v3 endpoint, while no longer supporting v2 testing or docs. Here is an example of a route re-direct for the NYT state endpoint:
```js
router.get('/v2/nyt/states/:state', async (req, res) => {
	const { state: queryState } = req.params;
	res.redirect(`/v3/covid19/nyt/states/${queryState || ''}`);
});
```

There are three parts to this issue:
- [ ] Redirects
- [ ] Delete v2 tests
- [ ] Deprecate v2 docs

**Comment by puf17640** [comment]
I will be working on this later on

**Comment by ebwinters** [comment]
We are no longer redirecting, but instead keeping the routes. This issue can be used to deprecate v2 testing and docs though.
