### ISSUE TITLE
[Feature Req] NYT lastDays parameter

### ISSUE THREAD

**Issue by ebwinters** [disease-sh/API#835]
https://disease.sh/v3/covid-19/nyt/counties endpoint takes a very long time to load, and while testing, sometimes causes timeouts. Only returning the last 15-30 days (will need to experiment with what is quicker) by default will be much better performance wise than returning the full data set. This will also speed up testing, while not sacrificing testing data correctness. 
We also have a `lastDays` param for the historical endpoint, so the logic can be copied.

**Comment by puf17640** [comment]
just started working on it, it's a pain in the ass because of how the NYT endpoints work (in particular the counties endpoint)

**Comment by puf17640** [comment]
I might work on this in the next few days, but this is really tedious work ...

**Comment by ebwinters** [comment]
@neo7337 is also working on this
