### ISSUE TITLE
[BUG] Check UK API status and adjust endpoint if necessary before letting the scraper fail

### ISSUE THREAD

**Issue by Collin-St** [disease-sh/API#857]
**Describe the bug**
The UK API has a staging and a prod endpoint. They keep breaking one, and leaving the other working.

**To Reproduce**
Where the bug occurring? Examples:
*CURRENTLY*
This endpoint hangs for 5 minutes before returning results: [prod endpoint](https://api.coronavirus.data.gov.uk/v1/data?filters=areaName=United%20Kingdom;areaType=overview&structure=%7B%22date%22:%22date%22,%22todayTests%22:%22newTestsByPublishDate%22,%22tests%22:%22cumTestsByPublishDate%22,%22testCapacity%22:%22plannedCapacityByPublishDate%22,%22newCases%22:%22newCasesByPublishDate%22,%22cases%22:%22cumCasesByPublishDate%22,%22hospitalized%22:%22hospitalCases%22,%22usedVentilationBeds%22:%22covidOccupiedMVBeds%22,%22newAdmissions%22:%22newAdmissions%22,%22admissions%22:%22cumAdmissions%22%7D)
- this endpoint returns the most up-to-date data, including the current date

This endpoint works as expected: [staging endpoint](https://api.coronavirus-staging.data.gov.uk/v1/data?filters=areaName=United%20Kingdom;areaType=overview&structure=%7B%22date%22:%22date%22,%22todayTests%22:%22newTestsByPublishDate%22,%22tests%22:%22cumTestsByPublishDate%22,%22testCapacity%22:%22plannedCapacityByPublishDate%22,%22newCases%22:%22newCasesByPublishDate%22,%22cases%22:%22cumCasesByPublishDate%22,%22hospitalized%22:%22hospitalCases%22,%22usedVentilationBeds%22:%22covidOccupiedMVBeds%22,%22newAdmissions%22:%22newAdmissions%22,%22admissions%22:%22cumAdmissions%22%7D)
- this endpoint returns up to yesterday's data

**Expected behavior**
Our UK scraper should first target the `prod` endpoint, and pass in a `timeout` config object to the `axios` request. If the request times out, then attempt hitting the `staging` endpoint. If both fail, let it hit the catch.

**Screenshots**

**Additional context**

**Comment by Collin-St** [comment]
Let me know if this makes sense. It aims to not fail - but maybe having the latest data is more important, and we should let it fail without updating redis?

**Comment by ebwinters** [comment]
This makes sense for all endpoints, trying a timeout instead of running forever. I think a valid timeout is 10s for a request, and on failure, we don't update redis. Our update checker that @puf17640 is doing will catch that

**Comment by ebwinters** [comment]
is this even happening anymore

**Comment by Collin-St** [comment]
not right now, but it probably will based on the fact that it's happened like 5x already. i've got a simple solution i'll throw up this week.
