### ISSUE TITLE
Delayed update of covid results

### ISSUE THREAD

**Issue by KevinNsimbe** [disease-sh/API#866]
Delayed update of covid results
My api only updates covid 19 results after a day

**Comment by KevinNsimbe** [comment]
https://disease.sh/v3/covid-19/countries/Uganda?yesterday=true&twoDaysAgo=true&strict=true&allowNull=false

That's my API url. But I only get updates after a full day.
Below is the application screenshot I created.

**Comment by ebwinters** [comment]
You have the yesterday parameter set to true. Take it out of the query.

**Comment by KevinNsimbe** [comment]
Thanks now everything works well.
