### ISSUE TITLE
Hash Apple redis data [Feature Req]

### ISSUE THREAD

**Issue by Collin-St** [disease-sh/API#872]
**Is your feature request related to a problem? Please describe.**
Similar to NYT, restructure the Apple redis data from a single key into a hash.

**Describe the solution you'd like**
The `covidapi:apple_all` string value will instead be a hash, where each hash field is a country from the dataset. Subregions will stay inside their respective country field.

The Apple utility logic will need to change to allow this. 

**Additional context**
The apple key is big (~39 MB) and is read on each request regardless of which country is being queried. Any request to this endpoint takes ~3-4 seconds, and that can be faster. Apple tests are also very slow and this might be related.
```
> redis-cli --bigkeys

# Scanning the entire keyspace to find biggest keys as well as
# average sizes per key type.  You can use -i 0.1 to sleep 0.1 sec
# per 100 SCAN commands (not usually needed).

[00.00%] Biggest string found so far 'covidapi:historical_v2_USA' with 19852458 bytes
[00.00%] Biggest hash   found so far 'covidapi:nyt_usa' with 32 fields
[47.62%] Biggest string found so far 'covidapi:apple_all' with 38928366 bytes

-------- summary -------

Sampled 21 keys in the keyspace!
Total key length in bytes is 434 (avg len 20.67)

Biggest   hash found 'covidapi:nyt_usa' has 32 fields
Biggest string found 'covidapi:apple_all' has 38928366 bytes

0 lists with 0 items (00.00% of keys, avg size 0.00)
3 hashs with 96 fields (14.29% of keys, avg size 32.00)
18 strings with 64601941 bytes (85.71% of keys, avg size 3588996.72)
0 streams with 0 entries (00.00% of keys, avg size 0.00)
0 sets with 0 members (00.00% of keys, avg size 0.00)
0 zsets with 0 members (00.00% of keys, avg size 0.00)
```

**Comment by Collin-St** [comment]
I can work on this over the next week or so unless anyone else is eager to work on it.

**Comment by ebwinters** [comment]
All you dude, you have the most context from the NYT refactor

**Comment by nibble0101** [comment]
@Collin-St  and @ebwinters . Has this been fixed? I don't see any activity here for quite some time. I am  new to redis but i would love to try fixing this if you don't mind.

**Comment by ebwinters** [comment]
@nibble0101 It has not. I'll assign it to you!

**Comment by puf17640** [comment]
@nibble0101 any updates on this?

**Comment by puf17640** [comment]
> @puf17640 Yeah. I have been quite busy in the last two months. Hopefully I will get time in the coming weeks. If you want to open a PR then please go ahead.

alright! I was just checking in to see if you are still going to work on this! 
i currently do not have any time to work on features for this project unfortunately, but the codebase is mostly @ebwinters and my code anyway 😉 looking forward to reviewing your code as soon as you find time to work on it, no stress! 👍🏻

**Comment by pujux** [comment]
Closed because of inactivity.
