### ISSUE TITLE
[BUG] Nigeria gov scraper failing

### ISSUE THREAD

**Issue by ebwinters** [disease-sh/API#882]
**Describe the bug**
Nigeria is failing because they have a modal over their actual site
https://covid19.ncdc.gov.ng/report/

We need to somehow simulate a button click on the button with `class=close`

**Comment by ebwinters** [comment]
Maybe not ... ?

**Comment by Collin-St** [comment]
The modal doesn't stop our requests from receiving the page data. i did see the scraper failing intermittently though, probably for some other reason
