### ISSUE TITLE
[Feature Req] Covid-19 projections from UCLA Statistical Machine Learning Lab

### ISSUE THREAD

**Issue by CovidMexico** [disease-sh/API#887]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An endpoint for Covid-19 projections from the UCLA Statistical Machine Learning Lab based on the data from this site: https://covid19.uclaml.org/index.html

- Include US and World projections.

**Additional context**
After looking for several models, found that the UCLA is one of the best. They compare some models here: https://covid19.uclaml.org/compare.html

- The data could be obtained from their github https://github.com/uclaml/ucla-covid19-forecasts/tree/master/projection_result
- This files are updated on a weekly basis.
- The data reuse license is CC-BY-4.0

**Comment by ebwinters** [comment]
I am hesitant on this, since we have defined our goal around reporting hard data, pulling from multiple sources. We had something similar to this come up a few months back, and decided against it -- @puf17640 @PrincessRavy @EliteDaMyth any thoughts?

**Comment by puf17640** [comment]
Well, the proposal back then was for us to create such a model, do I recall correctly?

**Comment by EliteDaMyth** [comment]
> I am hesitant on this, since we have defined our goal around reporting hard data, pulling from multiple sources. We had something similar to this come up a few months back, and decided against it -- @puf17640 @PrincessRavy @EliteDaMyth any thoughts?

I think it was when the data was already available in json format, we made thst decision. But this data seems to be available in only csv format, so serving it as json might not be a bad idea.

**Comment by ebwinters** [comment]
@CovidMexico Do you want to do this work?

**Comment by CovidMexico** [comment]
> @CovidMexico Do you want to do this work?

I'd like to, but actually I have zero experience with the way you guys work and the github plataform.

**Comment by ebwinters** [comment]
Github is a good platform to learn how to use. However, if you don't want to, maybe someone else will pick up the work. It will be the same as adding an endpoint, however, it will be directed to a subdomain for `disease.sh.predicitions/...`

**Comment by ebwinters** [comment]
Would you know how to add the feature to our code base locally @CovidMexico

**Comment by ryanlsmith4** [comment]
I would be interested in doing this if it's still on the table

**Comment by ebwinters** [comment]
@ryanlsmith4 it is still on the table. One thing we want to do is make a subdomain for predictions, since it is not hard data. But once you get the feature working down the line, we can coordinate setting up a CNAME record and routing it!

**Comment by ryanlsmith4** [comment]
Cool, Thanks @ebwinters starting dev soon!

**Comment by rohansp** [comment]
I would like to contribute to an enhancement or a bug or feature? I am experienced in ASP.NET, C#, JavaScript, SQL Server and Oracle.Any positive suggestions are welcome.

**Comment by puf17640** [comment]
> I would like to contribute to an enhancement or a bug or feature. I am experienced in ASP.NET, C#, JavaScript, SQL Server and Oracle.Any positive suggestions are welcome.

there currently aren't any free issues to work on, but you can have a look at the codebase and if there is something you would want to enhance, you can create an issue and we can discuss 👍

**Comment by ebwinters** [comment]
You can make a Nuget package as a Wrapper?

**Comment by rohansp** [comment]
@ebwinters Is this message for @ryanlsmith4 or me?

**Comment by ebwinters** [comment]
You lmao

**Comment by rohansp** [comment]
@ebwinters @puf17640 @ryanlsmith4  What is the package repository url? What files need to be in the package? Can you be more specific what needs to be done?

**Comment by ebwinters** [comment]
I don't really know what needs to be done, I've never written a NuGet package. We have other wrappers for Python and Node, so this is what I was thinking

**Comment by rohansp** [comment]
Okay. Will work on this item.

**Comment by ebwinters** [comment]
@rohansp any update

**Comment by rohansp** [comment]
Sorry for late response. I am tied up job change preps and my current day job. Anybody else wants to take this up can do so.

**Comment by nibble0101** [comment]
@ebwinters  You can assign it to me if no one is willing to take up this.

**Comment by ebwinters** [comment]
@nibble0101 I'm not sure how useful this would be TBH, and I don't really even want it in our API. Going to close it thanks for offering to pick it up though. If more useful work comes along I will let you know
