### ISSUE TITLE
[BUG] Info gets reset in the night before 12AM

### ISSUE THREAD

**Issue by TotallyNotInUse** [disease-sh/API#891]
**Describe the bug**
So the info about today's cases gets reset sometime in the night but before 12AM (CST) and it's annoying since data appears at 2PM and disappears some time around 7 to 8PM

**To Reproduce**
1. Use the [endpoint](https://disease.sh/v3/covid-19/countries/cr?yesterday=false) after 2PM but before 7PM and you'll get data from today.
2. Use the endpoint after 7PM and you'll get 0

**Expected behavior**
That the data would stay until 12AM
**Screenshots**
I currently don't have a screenshot for it but will provide as soon as I can.

**Additional context**
It may be because of timezones but having the data of today for only 6 hours a day seems a bit short.

**Comment by ebwinters** [comment]
TBH, I have no idea what you're trying to say here. The endpoint seems to be working fine -- as per Worldometers:
> The day is reset after midnight GMT+0
