### ISSUE TITLE
RAPS 404

### ISSUE THREAD

**Issue by ebwinters** [disease-sh/API#894]
Vaccine and therapeutics endpoints will not be updated, and tests will fail
https://www.raps.org/500.html?aspxerrorpath=/CMSPages/PortalTemplate.aspx

Source returning 404. If this keeps going for multiple days we will need to change something, but lets wait to see if it is transient

**Comment by phamleduy04** [comment]
maybe they fixed the bug, my PR unittest is passed. #890
