### ISSUE TITLE
Fix input size on home page

### ISSUE THREAD

**Issue by Dnguye92** [disease-sh/API#915]
**Describe the bug**
The size of the button and/or input is broken (shown below).

**To Reproduce**
Where the bug occurring? Examples:
- This is happening on the homepage and it seems like its happening only on chrome (Version 86.0.4240.75)

**Expected behavior**
- Input + button size should be consistent on all browsers and viewports

**Screenshots**
![image](https://user-images.githubusercontent.com/17717354/95962154-db583000-0dba-11eb-8a6f-e18e08b0e07a.png)

**Questions**
- Is there a reason why `vh` and `vw` are being used for padding inputs and buttons rather than just fixed pixels values?

**Comment by puf17640** [comment]
> Is there a reason why vh and vw are being used for padding inputs and buttons rather than just fixed pixels values?
Yeah, you don't use pixels for padding in responsive designs, I wouldn't have used vh and vw but it should be some relative value

**Comment by ebwinters** [comment]
@Dnguye92 are you planning to fix this? Can't repro - I use FF

**Comment by Dnguye92** [comment]
@ebwinters yeah I can fix it if you'd be kind enough to add a `hacktoberfest` tag on it :). I see it only on chrome desktop.

**Comment by ebwinters** [comment]
Make a PR and it will be added automatically @Dnguye92

**Comment by Dnguye92** [comment]
PR fix is [here](https://github.com/disease-sh/API/pull/916)
