### ISSUE TITLE
newRecovered Data

### ISSUE THREAD

**Issue by mohkhz2001** [disease-sh/API#928]
plz add  todayRecovered  to the API.
or tell me how can I use them.
thanks

**Comment by ebwinters** [comment]
@mohkhz2001 For what endpoint?

**Comment by mohkhz2001** [comment]
sorry I asked you that question by mistakes
https://disease.sh/v2/v2/historical/${arg} ==> how can I use this or https://disease.sh/v2/v2/historical ??

**Comment by neo7337** [comment]
@mohkhz2001  You can use the Docs for using the API: 
https://disease.sh/docs/

https://disease.sh/v3/covid-19/historical  --> for historical this would be the endpoint!

**Comment by mohkhz2001** [comment]
@neo7337 thank you.

**Comment by EliteDaMyth** [comment]
Assuming this is resolved. closing! if you have an other issues re-open or join our discord!
