### ISSUE TITLE
All the todayCases, todayRecovered and todayDeaths for a specific country are 0 while they still appear when looking for all countries. Please check back!

### ISSUE THREAD

**Issue by vutuanlinh2k2** [disease-sh/API#930]
**Describe the bug**

**To Reproduce**
Where the bug occurring? Examples:
- Live URL for endpoint?
- Server side?
- Development environment?

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vutuanlinh2k2** [comment]
<img width="498" alt="Screen Shot 2020-10-29 at 11 14 06 AM" src="https://user-images.githubusercontent.com/69841784/97524826-1c199100-19d8-11eb-8931-dd561c80e57f.png">
<img width="434" alt="Screen Shot 2020-10-29 at 11 14 39 AM" src="https://user-images.githubusercontent.com/69841784/97524838-1e7beb00-19d8-11eb-8f23-26eb34c37c1d.png">

**Comment by vutuanlinh2k2** [comment]
<img width="534" alt="Screen Shot 2020-10-29 at 11 17 12 AM" src="https://user-images.githubusercontent.com/69841784/97524983-68fd6780-19d8-11eb-8b9a-9b71d97a3fa6.png">
<img width="525" alt="Screen Shot 2020-10-29 at 11 17 33 AM" src="https://user-images.githubusercontent.com/69841784/97524984-6a2e9480-19d8-11eb-930e-e2d7479bec10.png">

**Comment by ebwinters** [comment]
if you actually visit the live endpoint, not the swagger example, you will see real data: https://disease.sh/v3/covid-19/countries/af?strict=true

Swagger is for documentation, the 0 simply represents that you can expect an `int` for that field.
