### ISSUE TITLE
Id for Sudan is incorrect

### ISSUE THREAD

**Issue by nibble0101** [disease-sh/API#931]
**Describe the bug**
When I fetch data for all countries using `https://disease.sh/v2/countries` and inspect the data  for Sudan, I get something like the following.
```js
{
updated: 1603972740905,
country: "Sudan",
countryInfo: {
_id: 736,
iso2: "SD",
iso3: "SDN",
lat: 15,
long: 30,
flag: "https://disease.sh/assets/img/flags/sd.png"
},
cases: 13765,
todayCases: 0,
deaths: 837,
todayDeaths: 0,
recovered: 6764,
todayRecovered: 0,
active: 6164,
critical: 0,
casesPerOneMillion: 312,
deathsPerOneMillion: 19,
tests: 0,
testsPerOneMillion: 0,
population: 44176327,
continent: "Africa",
oneCasePerPeople: 3209,
oneDeathPerPeople: 52779,
oneTestPerPeople: 0,
activePerOneMillion: 139.53,
recoveredPerOneMillion: 153.11,
criticalPerOneMillion: 0
}

```
You will notice that the value of `sudan.countryInfo._id` is `736`. My understanding is that this is [`ISO numeric code`](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) for Sudan (Correct me if I am wrong). `736` is  the numeric code for Sudan before secession of South Sudan. Currently Sudan's ISO code is 729 and that of South Sudan is 728. You can check from [here](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) and [here](https://www.iso.org/obp/ui/#iso:code:3166:SD)

You can investigate by fetching data from `https://disease.sh/v2/countries` .

**Comment by EliteDaMyth** [comment]
https://github.com/disease-sh/API/blob/master/utils/countries.js is the file to be edited, you're open to make a PR. If not I'll fix it in about an hour :)

**Comment by neo7337** [comment]
I would be changing the ISO numeric code to 729 for Sudan. I will raise the PR

**Comment by nibble0101** [comment]
> I would be changing the ISO numeric code to 729 for Sudan. I will raise the PR

@neo7337  It is okay. Go ahead and make a PR.

**Comment by EliteDaMyth** [comment]
#932 fixed.

**Comment by nibble0101** [comment]
@EliteDaMyth  How long will it take for this to be deployed?

**Comment by EliteDaMyth** [comment]
@nibble-4bits should be pretty much instant, the cache might make it take a bit longer, but it should be deployed and working by now

**Comment by nibble0101** [comment]
Thanks. It has been deployed.
