### ISSUE TITLE
[BUG]Specific country search data doesn't match all country data

### ISSUE THREAD

**Issue by Stijndes** [disease-sh/API#937]
When i request the data for Belgium from the specific endpoint i get this
![image](https://user-images.githubusercontent.com/36887748/98684669-bda0cb00-2366-11eb-8647-9dcf98a514ef.png)
which is correct as far as i know
but when requesting all countries you get this for Belgium, you can see the data doesn't match
![image](https://user-images.githubusercontent.com/36887748/98684751-d5784f00-2366-11eb-864b-8ac3476ecd76.png)
I don't know if the problem applies to other countries as well.

ps thanks for this api.

**Comment by ebwinters** [comment]
The responses are matching now, sometimes there are anomalies with the data due to caching. We update this data every 10 minutes, so it is possible one endpoint was behind the other, but now are fine:
https://disease.sh/v3/covid-19/countries/
https://disease.sh/v3/covid-19/countries/belgium
