### ISSUE TITLE
Worldometer cells - 

### ISSUE THREAD

**Issue by bhaidar** [disease-sh/API#940]
Hi,
While going through the code for the worldometer scraper, I noticed the following:

```
const mapRows = (_, row) => {
	const entry = { updated: Date.now() };
	const replaceRegex = /(\n|,)/g;
	cheerio(row).children('td').each((index, cell) => {
		const selector = columns[index];
		cell = cheerio.load(cell);
		switch (index) {
			case 0: {
				break;
			}
			case 1: {
				const countryInfo = nameUtils.getCountryData(cell.text().replace(replaceRegex, ''));
				entry[selector] = countryInfo.country || cell.text().replace(replaceRegex, '');
				delete countryInfo.country;
				entry.countryInfo = countryInfo;
				break;
			}
			case 15: {
				entry[selector] = cell.text();
				break;
			}
			default:
				entry[selector] = parseFloat(cell.text().replace(replaceRegex, '')) || null;
		}
	});
	// eslint-disable-next-line no-unused-expressions
	!entry.active && (entry.active = entry.cases - entry.recovered - entry.deaths);
	entry.activePerOneMillion = toPerOneMillion(entry.population, entry.active);
	entry.recoveredPerOneMillion = toPerOneMillion(entry.population, entry.recovered);
	entry.criticalPerOneMillion = toPerOneMillion(entry.population, entry.critical);
	return entry;
};
```

Every row in the worldometer table has 14 columns only. Starting with index 0 to 14. However, the code above checks for cell number 15. 

Is there something hidden in here or it needs a quick fix?

Thanks
Bilal

**Comment by ebwinters** [comment]
yes, it is for the continent name. If you want to PR a comment in the code to avoid future confusion, go ahead though.

![image](https://user-images.githubusercontent.com/4297028/99099816-f7f9aa80-25a8-11eb-8326-9e83f00b2f10.png)

**Comment by bhaidar** [comment]
Hi @ebwinters I can't see more than 15 columns hence index 15 is out of bounds. Maybe there is something I am not seeing in here.

![Screenshot 2020-11-14 at 7 59 34 AM](https://user-images.githubusercontent.com/1163421/99141035-845ea880-264f-11eb-8f7d-76d4598775b0.png)

**Comment by ebwinters** [comment]
Display none ...

**Comment by bhaidar** [comment]
Hi @ebwinters On the Worldometer page, there is a Columns selectbox. There are a few columns not selected by default. When selected, they appear inside the table. It seems Cheerio is bringing all those columns even if not selected inside the selectbox. Hence, it makes sense now.

**Comment by ebwinters** [comment]
@bhaidar if you want to make a comment in the code on this, feel free

**Comment by bhaidar** [comment]
@ebwinters Sure I will.
