### ISSUE TITLE
[Feature Req] Allow getting data for all US counties from /v3/covid-19/historical/usacounties/all endpoint

### ISSUE THREAD

**Issue by tazz4843** [disease-sh/API#943]
**Is your feature request related to a problem? Please describe.**
Currently, you have to iterate over all the states in `v3/covid-19/historical/usacounties` and make a request for each of those. This is ~60 extra requests to the API.

**Describe the solution you'd like**
Add a new endpoint: `v3/covid-19/historical/usacounties/all` that would return all of the US states data, as if you had made all the requests and appended each one to the end of a list.

**Additional context**
This would reduce load on the server (as long as the data is cached in memory) and shouldn't be too hard to implement (I assume it should be, I don't know any JS).

**Comment by ebwinters** [comment]
It's a good idea, but the data is too large to return over one endpoint, we tried this before actually. Not only is the endpoint extremely slow, but we are unable to test it as well
