### ISSUE TITLE
[BUG] government data for DE is outdated by 4 weeks

### ISSUE THREAD

**Issue by winnyschuster** [disease-sh/API#945]
**Describe the bug**
data seems not have been updated since Oct 21st(field: updated), cases reported are old too. The site used in the scraper however shows actual data as of today

**To Reproduce**
Where the bug occurring? Examples:
- ttps://disease.sh/v3/covid-19/gov/de
- Server side? happening in Browser
- Development environment? n/a

thanks!

**Expected behavior**
endpoint should show actual data
**Screenshots**

this shows data returned by browser(same result as when i tried few days ago)

`[{"updated":1603294353926,"province":"Baden-Württem­berg","cases":61694,"casePreviousDayChange":973,"casesPerHundredThousand":5419,"sevenDayCasesPerHundredThousand":48,"deaths":1946},{"updated":1603294353926,"province":"Bayern","cases":82102,"casePreviousDayChange":1222,"casesPerHundredThousand":7213,"sevenDayCasesPerHundredThousand":55,"deaths":2726},`

**Additional context**
[here's the site wth actual data](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html)

**Comment by ebwinters** [comment]
We stopped maintaining the gov endpoints since at least one was failing almost every day. If you would like to examine wh it is failing, make a fix, and PR, we will gladly accept it.

**Comment by winnyschuster** [comment]
code is working great if run in my own environment, looks like a (caching?) failure on disease.sh. thanks anyway
