### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jaspreetsethi** [disease-sh/API#951]
When trying to call the API from a java program keep getting this error
java.io.IOException: Server returned HTTP response code: 403 for URL: https://disease.sh/v3/covid-19/all

Expect the program to output the JSON response for the URL endpoint.

**Comment by ebwinters** [comment]
can you put your java code in the issue, as well as what country you are in? The endpoint is clearly working correctly in the US..

**Comment by jaspreetsethi** [comment]
Hi, thanks for the reply. I am trying to access it from Dubai, UAE. Here is the code:


package webscraper;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Scanner;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;


public class webData {
    public static void main(String[] args) {
        String url = "https://disease.sh/v3/covid-19/all";
      try{
        URL obj = new URL(url);
        HttpURLConnection con = (HttpURLConnection) obj.openConnection();
        
        con.setRequestMethod("GET");
        con.addRequestProperty("User-Agent", "Mozilla/5.0");
       
        int responseCode = con.getResponseCode();
        System.out.println("\nSending 'GET' request to URL : " + url); 
        System.out.println("Response Code : " + responseCode);
        Scanner s= new Scanner(obj.openStream());
       String inputLine="";
       while (s.hasNext()) { 
           inputLine+=s.nextLine();
        }
         JSONParser parser = new JSONParser ();
         JSONObject json=(JSONObject) parser.parse(inputLine);
      
        System.out.println(json);
          s.close();
      } catch(Exception ex){
          System.err.print(ex);
      }
}
}

And here is the error:
![image](https://user-images.githubusercontent.com/58161621/101601917-b37df500-3a16-11eb-9432-1d8640f400d6.png)

**Comment by ebwinters** [comment]
Try this URL instead: https://corona.lmao.ninja/v3/covid-19/all

**Comment by ebwinters** [comment]
closing unless that didn't work
