### ISSUE TITLE
Israel Gov API braking changes

### ISSUE THREAD

**Issue by meirroth** [disease-sh/API#953]
**Describe the bug**
It seems like the the the [API](https://datadashboard.health.gov.il/COVID-19/general) for Israel data has been modified so some data is missing at the [endpoint](https://disease.sh/v3/covid-19/gov/israel).

**To Reproduce**
Where the bug occurring? Examples:
- https://disease.sh/v3/covid-19/gov/israel
data missing for healthPersonnel

**Additional context**
I will look into it tomorrow and see if I can fix it myself.

**Comment by ebwinters** [comment]
Cool assigning to you
