### ISSUE TITLE
[QUESTION] Daily cases

### ISSUE THREAD

**Issue by ShowMeYourSkil** [disease-sh/API#959]
Hey, 

users of my covid dashboard have asked if it is possible to display the cases or deaths within 24 hours. Do you have a solution from your side how I can implement it?

**Comment by ebwinters** [comment]
Yeah can you send a link to your dashboard it would help me understand your question better. I think we have multiple solutions baked in though 🤠

**Comment by ShowMeYourSkil** [comment]
https://covid.progen-bot.de 

I want to create a new category called ,,Daily Cases". It will show the new cases in 24hours.

**Comment by ebwinters** [comment]
First of all here is a link to our docs: https://disease.sh/docs

Solution #1: `all?yesterday=true` will give you a row of data called `todayCases` which has the data. See here: https://disease.sh/v3/covid-19/all?yesterday=true

Solution #2: `historical/all?lastdays=2` will give you the last two days of cases/deaths/recoveries globally. Just subtract the previous day from the last entry. See here: https://disease.sh/v3/covid-19/historical/all?lastdays=2
