### ISSUE TITLE
About meaning of some fileds

### ISSUE THREAD

**Issue by josmanperez** [disease-sh/API#961]
Hello!, 

I want to know where I could find info about the meaning of some fields. For example, what is the difference between "cases" and "active":
 
`{
"cases": 1805633,
"active": 1756856,
}`

Thank you so much

**Comment by ebwinters** [comment]
What endpoint are you talking about? We have our sources posted in the docs/readme, so if you check those sources you will get a better idea (my guess is active is the number that is currently not recovered or dead). 

Also, if you want to extend this info into our docs by making a PR, that would be greatly appreciated

**Comment by josmanperez** [comment]
Hello, 

I'm talking about the `countries` endpoint, but also the `all` has that too. I search the docs on this page: https://corona.lmao.ninja/docs/#/COVID-19%3A%20Worldometers/get_v3_covid_19_all maybe I'm not going to the actual page... If you point me out in the right direction I would love to contribute :) 

Also, doing some test, it the **all** endpoint, the `updated` filed (this endpoint: `https://corona.lmao.ninja/v2/all?yesterday=1&allowNull=1` has a value that seems to be the Unix timestamp... but there has to be something wrong) because if you use a tool to convert that to "human" date it gives you a date like this: _10/18/52935 @ 11:56am (UTC)_

The result of calling that endpoint is:

```
{
    "updated": 1608325156585,
    "cases": 75277391,
    "todayCases": 738306,
    "deaths": 1667718,
    "todayDeaths": 12981,
    "recovered": 52842990,
    "todayRecovered": 478071,
    "active": 20766683,
    "critical": 107095,
    "casesPerOneMillion": 9657,
    "deathsPerOneMillion": 214,
    "tests": 1131090920,
    "testsPerOneMillion": 145117.62,
    "population": 7794304541,
    "oneCasePerPeople": null,
    "oneDeathPerPeople": null,
    "oneTestPerPeople": null,
    "activePerOneMillion": 2664.34,
    "recoveredPerOneMillion": 6779.69,
    "criticalPerOneMillion": 13.74,
    "affectedCountries": 220
}
```

It appears that you need to delete the last three numbers of that field in order to get a true date.

Thank you!

**Comment by jmariani** [comment]
“updated" field is a JS timestamp




Sent with Unibox

**Comment by nibble0101** [comment]
> It appears that you need to delete the last three numbers of that field in order to get a true date.

What service are you using to convert that date? When I run the code below, I get `Fri, 18 Dec 2020 20:59:16 GMT`.
```js
const date = new Date(1608325156585);
console.log(date.toUTCString());
```

**Comment by ebwinters** [comment]
@josmanperez we get the all and countries data from [here](https://www.worldometers.info/coronavirus/), so check their column descriptions to be sure.

It looks like @nibble0101 was able to turn the date into a valid date string.

As for contributing, it looks like Swagger has a way to update descriptions for returned fields: 
<img width="790" alt="image" src="https://user-images.githubusercontent.com/4297028/102691767-e5444800-41dc-11eb-97c7-a3ac9e7ebe9c.png">

You can add some for the return type of /all or /countries in our [JSON file](https://github.com/disease-sh/API/blob/master/public/apidocs/swagger_v3.json) which is used to generate the docs

**Comment by josmanperez** [comment]
> > It appears that you need to delete the last three numbers of that field in order to get a true date.
> 
> What service are you using to convert that date? When I run the code below, I get `Fri, 18 Dec 2020 20:59:16 GMT`.
> 
> ```js
> const date = new Date(1608325156585);
> console.log(date.toUTCString());
> ```

I was using **UNIX timestamp converter.** Since this is a JS timestamp (as you said). The UNIX timestamp is an integer that represents the number of seconds elapsed since January 1, 1970. The timestamp in JavaScript is expressed in milliseconds.

Thank you so much!
