### ISSUE TITLE
[Feature Req] Vaccine Related Stats

### ISSUE THREAD

**Issue by meirroth** [disease-sh/API#966]
**Is your feature request related to a problem? Please describe.**
This is more of a suggestion and less of a request.
Consider adding data on the number of people vaccinated worldwide and per country.

**Describe the solution you'd like**
Possible data source: 
https://ourworldindata.org/covid-vaccinations

Thank you!

**Comment by nibble0101** [comment]
> **Is your feature request related to a problem? Please describe.**
> This is more of a suggestion and less of a request.
> Consider adding data on the number of people vaccinated worldwide and per country.
> 
> **Describe the solution you'd like**
> Possible data source:
> https://ourworldindata.org/covid-vaccinations
> 
> Thank you!

That is a good suggestion. I like it.

**Comment by nibble0101** [comment]
@ebwinters  @EliteDaMyth  If you decide to include this data, I am interested in taking it up.

**Comment by EliteDaMyth** [comment]
> @ebwinters @EliteDaMyth If you decide to include this data, I am interested in taking it up.

sure! you are always open to make a PR!

**Comment by ebwinters** [comment]
just saw this. Looks like a great thing to add. @nibble0101 I'd add it under a route /covid-19/vaccine/tracking or something

**Comment by stijndcl** [comment]
> I'd add it under a route /covid-19/vaccine/tracking or something

If you decide to add per-country stats, could it be an idea to add it under `/covid-19/countries/[country_name]` instead? Just like the `cases` and `todayCases` fields, you'd have `vaccines` and `todayVaccines` or something similar. This way all stats of a country can still be retrieved in one go & are centralized in one place. It also makes it easier for people with applications to add this in (as it's just an extra field).

**Comment by meirroth** [comment]
> > I'd add it under a route /covid-19/vaccine/tracking or something
> 
> If you decide to add per-country stats, could it be an idea to add it under `/covid-19/countries/[country_name]` instead? Just like the `cases` and `todayCases` fields, you'd have `vaccines` and `todayVaccines` or something similar. This way all stats of a country can still be retrieved in one go & are centralized in one place. It also makes it easier for people with applications to add this in (as it's just an extra field).

I like that idea of having country specific vaccine data added to the current covid-19 country endpoint.
However there still needs to be a new endpoint for worldwide vaccine data.

**Comment by stijndcl** [comment]
> I like that idea of having country specific vaccine data added to the current covid-19 country endpoints.
> However there still needs to be a new endpoint for worldwide vaccine data.

Yes, one centralized place for vaccine-related info is definitely useful. I just thought that it would be cumbersome to get "country info", and then have to send another request to get another part of that country's info.

PS. Can't global vaccination stats (`total` and `today`) be added to `/covid-19/all`, considering that it also serves as a place to see global stats? In _addition to_ the new vaccine-specific endpoint you mentioned (which contains more data). This is just the same line of thought, as `/all` shows worldwide data so it sort of belongs in there too.

**Comment by ebwinters** [comment]
> > I like that idea of having country specific vaccine data added to the current covid-19 country endpoints.
> > However there still needs to be a new endpoint for worldwide vaccine data.
> 
> Yes, one centralized place for vaccine-related info is definitely useful. I just thought that it would be cumbersome to get "country info", and then have to send another request to get another part of that country's info.
> 
> PS. Can't worldwide vaccination stats (`total` and `today`) be added to `/covid-19/all`, considering that it also serves as a place to see global stats? In _addition to_ the new vaccine-specific endpoint you mentioned (which contains more data). This is just the same line of thought, as `/all` shows worldwide data so it sort of belongs in there too.

While this is a good idea, it isn't how our API is set up. We have different endpoints serving from different sources of data, and I don't want to mix that up for vaccines, especially since we already have a vaccine endpoint.

**Comment by DutchmanNL** [comment]
the current endpoints are not yet providing any vac data right ?
I have a source for Germany but that will not help for other countries :), can share if it helps ?

**Comment by ebwinters** [comment]
> the current endpoints are not yet providing any vac data right ?
> I have a source for Germany but that will not help for other countries :), can share if it helps ?

No, only vaccine progress data, and I think the source is sort of broken. This work would be very helpful

I'd rather just stick to this global source instead of a German endpoint, but if you want to work with @nibble0101 on it that would be nice
