### ISSUE TITLE
[BUG] Historical Recovered Numbers for USA

### ISSUE THREAD

**Issue by ohlesl1e** [disease-sh/API#972]
Describe the bug

In historical statistics, the recovered numbers for USA are 0 since Dec 14th 2020.

To Reproduce

    Live URL for endpoint : https://disease.sh/v3/covid-19/historical/USA?lastdays=all

**Comment by ebwinters** [comment]
Our source has made an announcement for why this happened:
Announcement: https://github.com/CSSEGISandData/COVID-19/issues/3464
Reasoning: https://covidtracking.com/about-data/faq#why-have-you-stopped-reporting-national-recoveries
