### ISSUE TITLE
Run only related tests on PR 

### ISSUE THREAD

**Issue by ebwinters** [disease-sh/API#974]
Would be cool if we had some way to run only the related testing files based on PR code changes. Sometimes PRs are blocked by unrelated testing failures, and this would be a cool devops item to look into.

**Comment by puf17640** [comment]
yeah that would actually be awesome but we would need some mechanism to choose which tests are going to be run which means we would need to make clear which test file is for which 'api file'

**Comment by puf17640** [comment]
if you have any ideas, go on, i probably dont have time to help much other than think it through with you but this is really a great idea

**Comment by ebwinters** [comment]
@puf17640 this is literally my job, my team is called "intelligent testing" lol. I'm thinking we have some sort of JSON file or something simple that maps files to tests, nothing too crazy tbh

Then during the YAML pipeline we do a couple things:
1. Have a script that takes changed files as the input
2. Script generates a .txt file on the machine with list of correlating test files
3. Call `test` command with the .txt file as an argument, similar to `test-single`

**Comment by puf17640** [comment]
sounds sexy! if you need my help, you know where to find me 👍

**Comment by ebwinters** [comment]
shouldn't be too hard, I already have a semi-working example on a feature branch. Basically
1. Get all changed files
2. Pass as a parameter to a short node script mapping files to test(s)
3. Write tests to a .txt file
4. Copy .txt file to docker image
5. If txt file is present in test image, pass it as input to the `mocha` command, similar to `test-single`

**Comment by ebwinters** [comment]
closes with #975
