### ISSUE TITLE
[QUESTION] -5,992,171 Recovered on Monday, Dec 14

### ISSUE THREAD

**Issue by meirroth** [disease-sh/API#977]
A while ago I notice a big drop in recoveries on the daily stats graph (see screenshot) -5,992,171 Recovered on Monday, Dec 14.
On Worldometer it shows 479,426 new recoveries on that day.
I thought it was an error and it would be fixed by the source. But Its still there... any idea why the big drop?

I am sorry if this is not the place to report issues related to the actual data, I was not sure what is the source used for that.

Graph on my [dashboard](https://coronaisrael.live/en/world/):
![image](https://user-images.githubusercontent.com/12494197/104858732-4add3e80-5919-11eb-9c27-8d979e8817af.png)
Graph on Worldometer
![image](https://user-images.githubusercontent.com/12494197/104858789-9a236f00-5919-11eb-81e6-2917fb5f0725.png)

Thanks

**Comment by meirroth** [comment]
Not sure how to remove label...

**Comment by ebwinters** [comment]
I looked at your dashboard and you are using this endpoint: https://disease.sh/v3/covid-19/historical/all?lastdays=all

TBH, I think you are doing calculations on your side that's messing this up. The data:
```md
12/13/20 | 47320022
12/14/20 | 41327851
```
The change between these two amounts happens to be 5992171, which you could've only gotten doing some data-transformation on your side

**Comment by meirroth** [comment]
Hi, 
The way I am doing it is by subtracting the previous day from the last entry, so here it would be:
New recoveries on 12/14/20 = (total recoveries to this date) 41327851 - (total recoveries the day before) 47320022
= -5992171.
I still don't understand...
Would you please explain it to me?

**Comment by ebwinters** [comment]
ok then that's where the negative number is coming from. It's not an issue with our API, seems to be something with your own code, so not much else I can help you with there
