### ISSUE TITLE
Repo link?

### ISSUE THREAD

**Issue by spekulatius** [disease-sh/API#981]
Hey,

great initiative! I wanted to leave you a hint on SEO / promoting your project further. The link in the repo settings is very beneficial for your SEO - maybe you want to add it in? Takes seconds, but is very good for your website!

![image](https://user-images.githubusercontent.com/8433587/105989669-e198c080-60ba-11eb-9c0a-6f9f3572dd51.png)

Cheers,
Peter

**Comment by ebwinters** [comment]
done, thanks!
