### ISSUE TITLE
The numbers coming from the API for many countries are not accurate[BUG]

### ISSUE THREAD

**Issue by AmrHE** [disease-sh/API#987]
**Describe the bug**
In other words, it returns zeros for today Cases, recovered, and deaths

**To Reproduce**
Where the bug occurring? Examples:

- Development environment

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ebwinters** [comment]
![image](https://user-images.githubusercontent.com/4297028/113609514-e2e5ec80-9619-11eb-80b9-1a1bcb0a0013.png)
You can see here, the source does not have this data in for many countries at the moment. We check it every 10 minutes, so when it appears, we will reflect those changes shortly after.
