### ISSUE TITLE
[Feature Req] Track US States Vaccine Coverage Data

### ISSUE THREAD

**Issue by comster** [disease-sh/API#990]
Like the Vaccine Coverage data for countries, we should include data from US States available from the same data source.

Data source: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv

Example endpoint: `/v3/covid-19/vaccine/coverage/states/{state}`

**Comment by ebwinters** [comment]
This is a good idea, if I get some time over the weekend I'll give it a go

**Comment by comster** [comment]
Sure, I'll give it a shot!
