### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by maltejur** [disease-sh/API#996]
Hello everyone,

Since the current website could still need some improvements, I've made a new website for this project. Let me know what you think about it. The newsletter thing still isn't integrated, so that's why I didn't open a pr and it currently ist still a bit broken on mobile.

https://github.com/maltejur/disease.sh
https://maltejur.github.io/disease.sh/

**Comment by puf17640** [comment]
Hey this looks really cool! Might need some polishing on the features section to not make it look a bit empty but I'm loving the general look of it! Great work! 

Are you a member of our Discord Server? If so, please contact us there so we can talk about integrating your version of the website! 👍🏻  If not, please join so we can do what I just said haha

**Comment by puf17640** [comment]
@ebwinters check this out mate!

**Comment by ebwinters** [comment]
This looks really good @maltejur. Once you fix mobile and some smaller things, we can help with the email stuff

**Comment by maltejur** [comment]
Okay, I've fixed the mobile version and polished some things.

> Might need some polishing on the features section to not make it look a bit empty

Hmm that's true. I am not really sure what to do there, but I'll probably just write some more text for the ones that still have a lot of white space. If you have any other things like this one that you don't like, just let me know.

**Comment by maltejur** [comment]
I've updated the feature section so that the text are all roughly the same size. I'm ready to integrate the newsletter, just tell me how to do it here or on the discord.

**Comment by ebwinters** [comment]
@maltejur is there a PR for this work?

Dealing with adding mail is straight forward. See this script section here: https://github.com/disease-sh/API/blob/5e1eaade8c6c778bef7c97702fc2297cd605ed76/public/index.ejs#L212

In this case, we're validating, parsing, an then calling an internal private endpoint. All you need to do is keep or move that logic to call the endpoint somewhere.
