### ISSUE TITLE
No popup when clicked on marker 

### ISSUE THREAD

**Issue by AndrejMeszarosDS** [disease-sh/API#998]
Try on homepage  https://react-leaflet.js.org with Safari.
Chrome and Firefox OK.

**Describe the bug**

**To Reproduce**
Where the bug occurring? Examples:
- Live URL for endpoint?
- Server side?
- Development environment?

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ebwinters** [comment]
What is this? There's no context

**Comment by AndrejMeszarosDS** [comment]
Hi
Sorry for this.

Best regards

Andrej


Používateľ Ethan Winters ***@***.***> sobota 8. mája 2021
napísal:
> What is this? There's no context
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/bhLX7TGKMBdbl2TjF2Ho4FtR2ynqQD_0Px1xXqpWvtypVN9rvMKDjILo16MPD9a_HiEAkR5gzDU2fvAx5juH2c7-Vny85I-ZAEbRqM_UcoNqrhGNQddOt2ie79kda3TwkNTaMSGFhdZPhJ5RTitmEHwB-T4ivZEQs5R_ifNeFGwuTQCgFTF7uGk2gNqU2CmfdITXw_nzAglFzdPVpGms1PClurXF2wKKvnxiA_5fjA=s0-d-e1-ft#https://github.com/notifications/beacon/ASVFEJRYY5ZLBUGT52WC4D3TMVQS5A5CNFSM44KSDTV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGHFXZHI.gif>

**Comment by puf17640** [comment]
I really don't get what is going on here so I will close this issue until there is any context to what you are having trouble with, I would appreciate if you could take a few seconds to write a few sentences instead of just sending in a link of an empty gif.
